# prometheus.yml
global:
    scrape_interval: 20s
    external_labels:
        monitor: 'prometheus'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['prometheus:9090']

  # - job_name: 'cadvisori'
  #   scrape_interval: 60s
  #   static_configs:
  #     - targets: ['<SERVER_IP>:<PORT>']

  # - job_name: 'node-exporter'
  #   scrape_interval: 60s
  #   static_configs:
  #     - targets: ['<SERVER_IP>:<PORT>']

  # - job_name: 'win11'
  #   static_configs:
  #   - targets: ['<SERVER_IP>:<PORT>']

  - job_name: 'speedtest-exporter'
    scrape_interval: 5m
    scrape_timeout: 90s # running speedtest needs time to complete
    static_configs:
      - targets: ['speedtest-exporter:9798']

  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 60s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://google.co.za
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox:9115'  # The blackbox exporter's real hostname:port.
