---
version: "3.3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8090:80
    restart: unless-stopped
