---
version: '3.3'
services:
  cadvisor:
    image: budry/cadvisor-arm # NOTE this is for ARM CPU
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8780:8080
    restart: unless-stopped
