---
version: '3.3'
services:
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    restart: unless-stopped
    volumes:
      - '/custom-docker-configs/alertmanager-config.yml:/etc/alertmanager/alertmanager.yml'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - '/custom-docker-configs/prometheus.yml:/etc/prometheus/prometheus.yml'
      - '/custom-docker-configs/alert.rules:/etc/prometheus/alert.rules'
      - '/custom-docker-configs/prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://<>SERVER-IP:9090'
    ports:
      - 9090:9090
    restart: unless-stopped
    
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter

    container_name: speedtest-exporter

    ports:
      - 9798:9798
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - PUID=472
      - PGID=472
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana
  
  blackbox:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana-storage: