version: '3.8'

services:
  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel-lgtm
    environment:
      - ENABLE_LOGS_ALL=true
      - OTEL_LOGS_EXPORTER=otlp  # Enable OTLP logs exporter
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317  # Send logs to OpenTelemetry
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent storage for Grafana
      - tempo_data:/var/lib/tempo      # Persistent storage for Tempo (traces)
      - loki_data:/var/lib/loki        # Persistent storage for Loki (logs)
      - mimir_data:/var/lib/mimir      # Persistent storage for Mimir (metrics)
    restart: unless-stopped

volumes:
  grafana_data:
    driver: local
  tempo_data:
    driver: local
  loki_data:
    driver: local
  mimir_data:
    driver: local
